/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import Sounds.BGMusic;
import game.ui.PickGamemode;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author Wein
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        bgm.playBackgroundAudio(filepath);
        pnlVisible();
        //background();
        
        try{
            File fontStyle = new File("src/fonts/8-bit-hud.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle);
            
            Font titleFont = font.deriveFont(44f);
            lblTitleScreen.setFont(titleFont);

            Font buttonFont = font.deriveFont(26f);
            lblPlay.setFont(buttonFont);   
            lblLeaderboard.setFont(buttonFont);
            lblExit.setFont(buttonFont);
            
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        
        
        
        lblPlay.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                lblPlay.setForeground(Color.YELLOW);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                fadeText(lblPlay, Color.WHITE);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                bgm.stopBackgroundAudio();
                new PickGamemode().setVisible(true);
                Menu.this.dispose();
            }
        }); 

        lblLeaderboard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                lblLeaderboard.setForeground(Color.YELLOW);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                fadeText(lblLeaderboard, Color.WHITE);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                bgm.stopBackgroundAudio();
                new Leaderboards().setVisible(true);
                Menu.this.dispose();
            }
        });         

        lblExit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                lblExit.setForeground(Color.YELLOW); 
            }

            @Override
            public void mouseExited(MouseEvent e) {
                fadeText(lblExit, Color.WHITE);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                bgm.stopBackgroundAudio();
                new Login().setVisible(true);
                Menu.this.dispose();
            }
        });  
        
        
    }

    private void fadeText(JLabel label, Color originalColor) {
        Timer timer = new Timer(10, new ActionListener() {
            float alpha = 1.0f;
            @Override
            public void actionPerformed(ActionEvent e) {
                alpha -= 0.05f;
                if (alpha <= 0.0f) {
                    ((Timer) e.getSource()).stop();
                    label.setForeground(originalColor);
                } else {
                    label.setForeground(new Color(
                            (int) (originalColor.getRed() * alpha + 255 * (1 - alpha)),
                            (int) (originalColor.getGreen() * alpha + 255 * (1 - alpha)),
                            (int) (originalColor.getBlue() * alpha + 255 * (1 - alpha))
                    ));
                }
            }
        });
        timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    String filepath="src/Sounds/background2.wav";
    BGMusic bgm=new BGMusic(1);
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleScreen = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        lblLeaderboard = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        pnlChoose = new javax.swing.JPanel();
        btnPVP = new javax.swing.JButton();
        btnStory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleScreen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitleScreen.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleScreen.setText("Galactic Wanderers");
        getContentPane().add(lblTitleScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        lblPlay.setForeground(new java.awt.Color(255, 255, 255));
        lblPlay.setText("Play");
        getContentPane().add(lblPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        lblLeaderboard.setForeground(new java.awt.Color(255, 255, 255));
        lblLeaderboard.setText("Leaderboard");
        getContentPane().add(lblLeaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Log out");
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/GWTitleScreen.gif"))); // NOI18N
        lblBackground.setAlignmentY(0.0F);
        lblBackground.setMaximumSize(new java.awt.Dimension(1280, 768));
        lblBackground.setMinimumSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pnlChoose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPVP.setText("PVP");
        btnPVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVPActionPerformed(evt);
            }
        });
        pnlChoose.add(btnPVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btnStory.setText("Story Mode");
        pnlChoose.add(btnStory, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlChoose.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        getContentPane().add(pnlChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 780, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPVPActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        pnlChoose.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed
public void background(){
        String filepath="src/Sounds/background2.wav";
        
        try{
            File musicpath=new File(filepath);
            AudioInputStream audioInput= AudioSystem.getAudioInputStream(musicpath);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        }catch(Exception ex){
         
     }
                            
     }
public void pnlVisible(){
   pnlChoose.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPVP;
    private javax.swing.JButton btnStory;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblTitleScreen;
    private javax.swing.JPanel pnlChoose;
    // End of variables declaration//GEN-END:variables
}
