package game.gameLogic;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Wein
 */
//import practice.GameState;
//import java.lang.Thread;
import Sounds.BGMusic;
import game.Menu;
import game.characters.Character;
import game.ui.PVPCharacterPicking;
import java.awt.Button;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

//import javax.swing.Timer;

public class pvp extends javax.swing.JFrame implements GameState {

    /**
     * Creates new form pvp
     */
    Character objChar1 = new Character();
    Character objChar2 = new Character();
    String ch;
    public pvp() {}
    
    public pvp(int choice1,int choice2, int background,String ch) {
        initComponents();
        hideMenus();
        this.choice1=choice1;
        this.choice2=choice2;
        this.bg=background;
        this.ch=ch;
        initBackground(background);
        objChar1.setChoice(choice1);
        objChar2.setChoice(choice2);
        System.out.println(choice1);
        System.out.println(choice2);
        initCharacters(choice1,choice2);
        bgm.playBackgroundAudio(fileName);
        playerHp();
        timer();
  
        
        try{
            File fontStyle = new File("src/fonts/8-bit-hud.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle);
            
            Font timerFont = font.deriveFont(14f);
            lblTime.setFont(timerFont);

            Font nameFont = font.deriveFont(12f);
            p1Name.setFont(nameFont);
            p2Name.setFont(nameFont);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int choice1;
    int choice2;
    int bg;
    int checker=1;
    int player1hp=100;
    int player2hp=100;
    Character player1=new Character();
    Character player2=new Character();
    int turncount=0;
    int counter=31;
    int counter2=1000;
    int pauseCounter=0;
    int pause=0;
    String fileName="src/Sounds/pvp2.wav";
    BGMusic bgm=new BGMusic(1);
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWin = new javax.swing.JPanel();
        btnCharPicking = new javax.swing.JButton();
        btnRematch = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnUnpause = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        btnPause = new javax.swing.JButton();
        lblPlayer1 = new javax.swing.JLabel();
        pgPlayer2 = new javax.swing.JProgressBar();
        p1Name = new javax.swing.JLabel();
        pgPlayer1 = new javax.swing.JProgressBar();
        p2Name = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        btnskill1 = new javax.swing.JButton();
        btnskill2 = new javax.swing.JButton();
        btnskill3 = new javax.swing.JButton();
        btnskill4 = new javax.swing.JButton();
        btn2skill1 = new javax.swing.JButton();
        btn2skill2 = new javax.swing.JButton();
        btn2skill3 = new javax.swing.JButton();
        btn2skill4 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactic Wanderers");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCharPicking.setText("Character Picking");
        btnCharPicking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharPickingActionPerformed(evt);
            }
        });
        pnlWin.add(btnCharPicking, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        btnRematch.setText("Rematch");
        btnRematch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRematchActionPerformed(evt);
            }
        });
        pnlWin.add(btnRematch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        btnReturn.setText("Menu");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        pnlWin.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        getContentPane().add(pnlWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 510, 570));

        btnUnpause.setText("Unpause");
        btnUnpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnpauseActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnpause, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("30");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 43, -1));

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        getContentPane().add(btnPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 63, -1));

        lblPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Brett/idle/char-brettIdle-unscreen.gif"))); // NOI18N
        getContentPane().add(lblPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 225, 225));

        pgPlayer2.setBackground(new java.awt.Color(255, 255, 255));
        pgPlayer2.setForeground(new java.awt.Color(255, 51, 51));
        pgPlayer2.setString("");
        getContentPane().add(pgPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 500, 23));

        p1Name.setForeground(new java.awt.Color(255, 255, 255));
        p1Name.setText("Player 1");
        getContentPane().add(p1Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 235, -1));

        pgPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        pgPlayer1.setForeground(new java.awt.Color(255, 0, 0));
        pgPlayer1.setString("");
        pgPlayer1.setStringPainted(true);
        getContentPane().add(pgPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 540, 23));

        p2Name.setForeground(new java.awt.Color(255, 255, 255));
        p2Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        p2Name.setText("Player 2");
        p2Name.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(p2Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 256, -1));

        lblPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gabe/Idle/char-gabeIdle-unscreen.gif"))); // NOI18N
        getContentPane().add(lblPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 225, 225));

        btnskill1.setText("Skill 1");
        btnskill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnskill1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnskill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        btnskill2.setText("Skill 2");
        getContentPane().add(btnskill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        btnskill3.setText("Skill 3");
        getContentPane().add(btnskill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        btnskill4.setText("Skill 4");
        getContentPane().add(btnskill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        btn2skill1.setText("Skill 1");
        btn2skill1.setToolTipText("");
        btn2skill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2skill1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2skill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, -1, -1));

        btn2skill2.setText("Skill 2");
        getContentPane().add(btn2skill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, -1, -1));

        btn2skill3.setText("Skill 3");
        getContentPane().add(btn2skill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, -1, -1));

        btn2skill4.setText("Skill 4");
        getContentPane().add(btn2skill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 560, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pvpScreen.gif"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void hideMenus(){
    pnlWin.setVisible(false);
}
    public void WinMenu(){
        lblPlayer1.setVisible(false);
        lblPlayer2.setVisible(false); 
        p1Name.setVisible(false);
        p2Name.setVisible(false);
        lblTime.setVisible(false);
        pgPlayer1.setVisible(false);
        pgPlayer2.setVisible(false);
        setVisibleFalse();
        pnlWin.setVisible(true);
    }
    public void initBackground(int background) {
        switch (background)
        {
            case 1: lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/brettbg.gif")));
                break;
            case 2: lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/gabebg.gif")));
                break;
            case 3: lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/miganbg.gif")));
                break;
            case 4: lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/sirKhaibg.gif")));
                break;
            default:;
        }
    }
    
    public void initCharacters(int choice1, int choice2) {
        switch (choice1)
        {
            case 1: lblPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Brett/idle/char-brettIdle-unscreen.gif")));
                break;
            case 2: lblPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gabe/idle/char-gabeIdle-unscreen.gif")));
                break;
            case 3: lblPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Migantron/idle/char-miganIdle-unscreen.gif")));
                break;
            case 4: lblPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sir Kai/idle/char-skIdle-unscreen.gif")));
                break;
            default:;
        }
        
        switch (choice2)
        {
            case 1: lblPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Brett/idle/char-brettIdle-mir-unscreen.gif")));
                break;
            case 2: lblPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gabe/idle/char-gabeIdle-mir-unscreen.gif")));
                break;
            case 3: lblPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Migantron/idle/char-miganIdle-mir-unscreen.gif")));
                break;
            case 4: lblPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sir Kai/idle/char-skIdle-mir-unscreen.gif")));
                break;
            default:;
        }
    }
    
    public void characterDamage(){
     //wala pay character
    }
   public void setBtnVisible(Button btn){
       btn.setVisible(true);
   }
   
    @Override
    public void turn(){
        if(turncount==1){
            btnskill1.setVisible(true);
            btnskill2.setVisible(true);
            btnskill3.setVisible(true);
            btnskill4.setVisible(true);
      
            btn2skill1.setVisible(false);
            btn2skill2.setVisible(false);
            btn2skill3.setVisible(false);
            btn2skill4.setVisible(false);
            counter=31;
        
        } else if(turncount==2){
            btnskill1.setVisible(false);
            btnskill2.setVisible(false);
            btnskill3.setVisible(false);
            btnskill4.setVisible(false);
            
            btn2skill1.setVisible(true);
            btn2skill2.setVisible(true);
            btn2skill3.setVisible(true);
            btn2skill4.setVisible(true);
            counter=31;
        }
    }
    
    public void setVisibleFalse() {
        btnPause.setVisible(false);
        
        btnskill1.setVisible(false);
        btnskill2.setVisible(false);
        btnskill3.setVisible(false);
        btnskill4.setVisible(false);
        
        btn2skill1.setVisible(false);
        btn2skill2.setVisible(false);
        btn2skill3.setVisible(false);
        btn2skill4.setVisible(false);
    }
    
    public void setFalse(){
       setVisibleFalse();
       btnUnpause.setVisible(false); // INDIVIDUAL CHANGE, SINCE IT HAS DIFFERENT VALUE ON PAUSE
    }
    
    @Override
    public void pause(){
        setVisibleFalse();
        btnUnpause.setVisible(true); // INDIIVIDUAL CHANGE, SINCE IT HAS DIFFERENT VALUE ON setFALSE
    }
    
    @Override
     public void gameWin(){
         if(player2hp<=0||player1hp<player2hp&&counter==0){
             player2hp=0;
             pgPlayer2.setValue(player2hp);
             setFalse();
             whenWin();
             JOptionPane.showMessageDialog(null, "Player 1 Wins","Congratulations",JOptionPane.INFORMATION_MESSAGE); 
             WinMenu();
             
         }else if(player1hp<=0){
             player1hp=0;
             pgPlayer1.setValue(player1hp);
             setFalse();
             whenWin();
             JOptionPane.showMessageDialog(null, "Player 2 Wins");
             WinMenu();
             
             
         }
     }
     
     @Override
     public void timer(){
         Thread time=new Thread(){
           public void run(){
               while(checker==1){
                   if(pause==0){
                       counter2--;
                       counter2--;
                   if(counter2==0){ 
                           counter--;
                           lblTime.setText(""+counter);   
                           if(counter==25){
                            if(turncount==1){
                            turncount=2;
                            turn();
                            checker=1;
                            
                        }else if(turncount==2){
                            turncount=1;  
                            turn();
                            checker=1;
                                
                        }
                       }
                       
                       }
                       
                   }
                   
                   
               }
           }
       };
         
       time.start();
       
     }
     
     public void playerHp(){
         if(turncount==0){
             pgPlayer1.setValue(player1hp);
             pgPlayer2.setValue(player2hp);
             turncount=1;
             turn();
             
         }
         else if(turncount==1){
             pgPlayer1.setValue(player1hp);
             gameWin();
            
             
         }else if(turncount==2){
             pgPlayer2.setValue(player2hp);
             gameWin();
              
         }
     }
     @Override
     public void unPause(){
         pause=0;
          btnPause.setVisible(true);
        btnUnpause.setVisible(false);
        if(turncount==1){
        btnskill1.setVisible(true);
        btnskill2.setVisible(true);
        btnskill3.setVisible(true);
        btnskill4.setVisible(true);
        }else{
        btn2skill1.setVisible(true);
        btn2skill2.setVisible(true);
        btn2skill3.setVisible(true);
        btn2skill4.setVisible(true);
     }
    }
     
 public void whenWin(){
        bgm.stopBackgroundAudio();
        String filepath="src/Sounds/victory.wav";
        pause=1;
        try{
            File musicpath=new File(filepath);
            AudioInputStream audioInput= AudioSystem.getAudioInputStream(musicpath);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        }catch(Exception ex){
         
     }
 }
     
     public void whenDamage(){
        String filepath="src/Sounds/roblox.wav";
        
        try{
            File musicpath=new File(filepath);
            AudioInputStream audioInput= AudioSystem.getAudioInputStream(musicpath);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        }catch(Exception ex){
         
     }
                
                
            
     }
    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:     
                pause=1;  
                pause();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnskill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnskill1ActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int dmg=rand.nextInt(100)+1;
        player2hp-=dmg;
        turncount=2;
        turn();
         whenDamage();
        playerHp();
      
    }//GEN-LAST:event_btnskill1ActionPerformed

    private void btnUnpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnpauseActionPerformed
        // TODO add your handling code here:
        pause=0;
        unPause();
        btnUnpause.setVisible(false);
        btnPause.setVisible(true);
    }//GEN-LAST:event_btnUnpauseActionPerformed

    private void btn2skill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2skill1ActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int dmg=rand.nextInt(100)+1;
        player1hp-=dmg;
        turncount=1;
        turn();
        whenDamage();
        playerHp();
       
    }//GEN-LAST:event_btn2skill1ActionPerformed

    private void btnRematchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRematchActionPerformed
        // TODO add your handling code here:
        new pvp(choice1,choice2,bg,ch).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRematchActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        new Menu(ch).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCharPickingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharPickingActionPerformed
        // TODO add your handling code here:
        new PVPCharacterPicking(ch).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCharPickingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pvp().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2skill1;
    private javax.swing.JButton btn2skill2;
    private javax.swing.JButton btn2skill3;
    private javax.swing.JButton btn2skill4;
    private javax.swing.JButton btnCharPicking;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnRematch;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUnpause;
    private javax.swing.JButton btnskill1;
    private javax.swing.JButton btnskill2;
    private javax.swing.JButton btnskill3;
    private javax.swing.JButton btnskill4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel p1Name;
    private javax.swing.JLabel p2Name;
    private javax.swing.JProgressBar pgPlayer1;
    private javax.swing.JProgressBar pgPlayer2;
    private javax.swing.JPanel pnlWin;
    // End of variables declaration//GEN-END:variables
}
