/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game.gameLogic;

import entities.Boss;
import entities.Entity;
import entities.Mob;
import entities.Player;
import java.util.Random;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import static java.lang.Thread.sleep;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Wein
 */
public class StoryMode extends javax.swing.JFrame implements GameState {

    /**
     * Creates new form StoryMode
     */
    public StoryMode() {
        initComponents();
        try{
            File fontStyle = new File("src/fonts/8-bit-hud.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle);
            
            Font timerFont = font.deriveFont(14f);
            lblTime.setFont(timerFont);

            Font nameFont = font.deriveFont(12f);
           lblPlayer.setFont(nameFont);
           lblEnemy.setFont(nameFont);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        
       gamePlay();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTest = new javax.swing.JLabel();
        lblTest1 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        lblplay = new javax.swing.JLabel();
        pnlDialogue = new javax.swing.JPanel();
        lblDialogue = new javax.swing.JLabel();
        pgEnemy = new javax.swing.JProgressBar();
        pgPlayer = new javax.swing.JProgressBar();
        btnSkill1 = new javax.swing.JButton();
        btnSkill2 = new javax.swing.JButton();
        btnSkill3 = new javax.swing.JButton();
        btnSkill4 = new javax.swing.JButton();
        enemy1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnPause = new javax.swing.JButton();
        lblPlayer = new javax.swing.JLabel();
        lblEnemy = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnUnpause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTest.setForeground(new java.awt.Color(255, 255, 255));
        lblTest.setText("30");
        getContentPane().add(lblTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 270, 20));

        lblTest1.setForeground(new java.awt.Color(255, 255, 255));
        lblTest1.setText("30");
        getContentPane().add(lblTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 270, 20));

        lblTest2.setForeground(new java.awt.Color(255, 255, 255));
        lblTest2.setText("30");
        getContentPane().add(lblTest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 270, 20));

        lblplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alienpls3-alienpls.gif"))); // NOI18N
        getContentPane().add(lblplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, 110));

        pnlDialogue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDialogue.setText("WHAT IN THE FUCKING WORLD ARE YOU DOING");
        lblDialogue.setToolTipText("");
        pnlDialogue.add(lblDialogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(pnlDialogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1280, 100));
        getContentPane().add(pgEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 430, 30));
        getContentPane().add(pgPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 430, 30));

        btnSkill1.setText("Skill1");
        btnSkill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btnSkill2.setText("Skill2");
        btnSkill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        btnSkill3.setText("Skill3");
        btnSkill3.setToolTipText("");
        btnSkill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        btnSkill4.setText("Skill4");
        btnSkill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkill4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy1.gif"))); // NOI18N
        getContentPane().add(enemy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 520, 470));

        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("30");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 60, 270, 20));

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        getContentPane().add(btnPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        lblPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer.setText("Player 1");
        getContentPane().add(lblPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblEnemy.setForeground(new java.awt.Color(255, 255, 255));
        lblEnemy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEnemy.setText("EnemyName");
        lblEnemy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 256, 20));

        lblBackground.setForeground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pvpScreen.gif"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnpause.setText("Unpause");
        btnUnpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnpauseActionPerformed(evt);
            }
        });
        pnlMenu.add(btnUnpause, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 149, -1, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 320, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        pause=1;
        pause();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnUnpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnpauseActionPerformed
        // TODO add your handling code here:
        pause=0;
        unPause();
    }//GEN-LAST:event_btnUnpauseActionPerformed

    private void btnSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill1ActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int damage=rand.nextInt(100)+1;
        if(enemy!=4){
            stud.damage(damage);
        }else if(enemy==4){
            kai.damage(damage);
        }
        turncount=2;
        enemyDamages();
        gameWin();
        changeEnemy();
        lblTest2.setText(""+enemy);
    }//GEN-LAST:event_btnSkill1ActionPerformed

    private void btnSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill2ActionPerformed
        // TODO add your handling code here:
        turncount=2;
        turn();
        
    }//GEN-LAST:event_btnSkill2ActionPerformed

    private void btnSkill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill3ActionPerformed
        // TODO add your handling code here:
        turncount=2;
        turn();
    }//GEN-LAST:event_btnSkill3ActionPerformed

    private void btnSkill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill4ActionPerformed
        // TODO add your handling code here:
        turncount=2;
        turn();
    }//GEN-LAST:event_btnSkill4ActionPerformed
    
    int mili=0;
    int sec=0;
    int min=0;
    int hour=0;
    int day=0;
    int pause=0;
    int playerHP=100;
    int enemy=1;//counter para mo change ang enemy icon og background tas dialogue probably
    int win=0;//to stop timer after winning;
    int retry;// checker what type of retry check retry method
    int turncount=1;
    Entity stud=new Mob(100);//mob damage increase per %5(tbd)
    Entity player=new Player(200);
    Entity kai=new Boss(500);
    
    int lblTextLength=0;
    Timer tm;
    int counter=0;
   
    
   public void dialogue(){
        String txt=lblDialogue.getText();
        lblTextLength = txt.length();
        
        tm= new Timer(50, (ActionEvent arg0) -> {
            counter++;
            if(counter>lblTextLength){
                lblDialogue.setText("");
                counter=0;
            }else{
                lblDialogue.setText(txt.substring(0,counter));
            }
        });
        tm.start();
 }
    
    public void enemyDamages(){
        turn();
        pgPlayer.setValue(player.getHP());
        lblTest.setText(""+player.getHP());
        if(enemy!=4){
        pgEnemy.setValue(stud.getHP());
        }else{
        pgEnemy.setValue(kai.getHP());
    }
    }
    
    public void setVisible(){
        if(turncount==2){
        btnSkill1.setVisible(false);
        btnSkill2.setVisible(false);
        btnSkill3.setVisible(false);
        btnSkill4.setVisible(false);
        }else if(turncount==1){
        btnSkill1.setVisible(true);
        btnSkill2.setVisible(true);
        btnSkill3.setVisible(true);
        btnSkill4.setVisible(true);
        }
    }
    @Override
     public void pause(){
        pnlMenu.setVisible(true);
        //lblplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alien.gif")));
     }
    public void changeEnemy(){
        if(enemy==1){
                    //System.out.println("I am your first enemy");
                    gameWin();
                    enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy1.gif")));
                    pgPlayer.setValue(player.getHP());
                    
                }else if(enemy==2){ 
                    //System.out.println("I am your second enemy");
                    pgEnemy.setValue(stud.getHP());
                    gameWin();
                    enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy2.gif")));
                    pgPlayer.setValue(player.getHP());
                }else if(enemy==3){
                    //System.out.println("I am your last enemy");
                    pgEnemy.setValue(stud.getHP());
                    gameWin();
                    enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy3.gif")));
                    pgPlayer.setValue(player.getHP());
                }else if(enemy==4){
                    pgEnemy.setValue(kai.getHP());
                    gameWin();
                    enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy4.gif")));
                    pgPlayer.setValue(player.getHP());
                }
    }
    public void gameWin(){
        if(stud.getHP()<=0&&enemy!=4){
            enemy++;
           stud.addHP(100);
           
        }else if(player.getHP()<=0&&enemy!=4){
            JOptionPane.showMessageDialog(this, "YOU LOSE", "Good Game", JOptionPane.INFORMATION_MESSAGE);
        }else if(kai.getHP()<=0){
            //Dialogue you finish the game
            //Add timer to database
            JOptionPane.showMessageDialog(this, "YOU WIN", "Good Game", JOptionPane.INFORMATION_MESSAGE);
            win=1;
        }
    }

    public void retry(){
        if(retry==1){
            //Reset only stage but timer is running;
        }else if(retry==2){
            //Reset tanan asta stage back to 0 also ang timer;
        }
    }
    
    public void gamePlay(){
        Thread game=new Thread(){
            public void run(){
            dialogue();
            timer();
            }
        };
        game.start();
    }
    @Override
    public void timer(){
        Thread time=new Thread(){
           public void run(){
               while(win==0){
                   if(pause==0){
                     try{
                       sleep(1);
                       mili++;
                       mili++;
                       lblTime.setText(""+day+"|"+hour+"|"+min+"|"+sec+"|"+mili);
                       if(mili >=1000){ 
                           mili=0;
                           sec++;
                           if(sec>=60){
                            sec=0;
                            min++;
                                if(min>=60){
                                min=0;
                                hour++;
                                    if(hour>=24){
                                    day++;
                                    }
                                }
                                
                           }
                       }   
                     }catch(Exception e){
                         
                     }
                    }
                   
                }
           }                
        };        
       time.start();
    }
    
    @Override
    public  void turn(){
        if(turncount==2){
            setVisible();
            Random rand=new Random();
            int damage=rand.nextInt(10)+1;
            player.damage(damage);
            turncount=1;
            setVisible();
        }
    }
    
    public void unPause(){
        pnlMenu.setVisible(false);
        Thread time=new Thread(){
           public void run(){
               while(win==0){
                   if(pause==0){
                     try{
                       sleep(1);
                       mili++;
                       mili++;
                       lblTime.setText(""+day+":"+hour+":"+min+":"+sec+":"+mili);
                       if(mili >=1000){ 
                           mili=0;
                           sec++;
                           if(sec>=60){
                            sec=0;
                            min++;
                                if(min>=60){
                                min=0;
                                hour++;
                                    if(hour>=24){
                                    day++;
                                    }
                                }
                                
                           }
                       }   
                     }catch(Exception e){
                         
                     }
                    }
                   
                }
           }                
        };        
       time.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoryMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoryMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnSkill1;
    private javax.swing.JButton btnSkill2;
    private javax.swing.JButton btnSkill3;
    private javax.swing.JButton btnSkill4;
    private javax.swing.JButton btnUnpause;
    private javax.swing.JLabel enemy1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDialogue;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblplay;
    private javax.swing.JProgressBar pgEnemy;
    private javax.swing.JProgressBar pgPlayer;
    private javax.swing.JPanel pnlDialogue;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
