/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game.ui;

import game.*;
import game.gameLogic.StoryMode;
import game.gameLogic.pvp;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author Wein
 */
public class PickGamemode extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public PickGamemode() {
        initComponents();
        pnlVisible();
        //background();
        this.setResizable(false);
        
        try{
            File fontStyle = new File("src/fonts/8-bit-hud.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle);
            
            Font titleFont = font.deriveFont(44f);
            lblTitleScreen.setFont(titleFont);

            Font buttonFont = font.deriveFont(32f);
            lblStorymode.setFont(buttonFont);   
            lblPvp.setFont(buttonFont);
            lblExit.setFont(buttonFont);
            
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        
        lblStorymode.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //TODO
                PickGamemode.this.dispose();
                new StoryMode().setVisible(true);
            }
        }); 
        
        lblPvp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                PickGamemode.this.dispose();
                new PVPCharacterPicking().setVisible(true);
            }
        });         
        
        
        lblExit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new Menu().setVisible(true);
                PickGamemode.this.dispose();                
            }
        });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JPPvp = new javax.swing.JPanel();
        PVPbg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JPStory = new javax.swing.JPanel();
        SMbg = new javax.swing.JLabel();
        lblStorymode = new javax.swing.JLabel();
        lblPvp = new javax.swing.JLabel();
        lblTitleScreen = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPPvp.setOpaque(false);
        JPPvp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPPvpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPPvpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPPvpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPPvpLayout = new javax.swing.GroupLayout(JPPvp);
        JPPvp.setLayout(JPPvpLayout);
        JPPvpLayout.setHorizontalGroup(
            JPPvpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPPvpLayout.setVerticalGroup(
            JPPvpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(JPPvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 420));
        JPPvp.getAccessibleContext().setAccessibleParent(lblBackground);

        PVPbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pvpScreenSmol.gif"))); // NOI18N
        jPanel2.add(PVPbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 330));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 400, 350));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPStory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPStory.setOpaque(false);
        JPStory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPStoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPStoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPStoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPStoryLayout = new javax.swing.GroupLayout(JPStory);
        JPStory.setLayout(JPStoryLayout);
        JPStoryLayout.setHorizontalGroup(
            JPStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JPStoryLayout.setVerticalGroup(
            JPStoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(JPStory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 420));

        SMbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/SMbg.gif"))); // NOI18N
        jPanel1.add(SMbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 400, 350));
        jPanel1.getAccessibleContext().setAccessibleName("");

        lblStorymode.setForeground(new java.awt.Color(255, 255, 255));
        lblStorymode.setText("Story Mode");
        getContentPane().add(lblStorymode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        lblPvp.setForeground(new java.awt.Color(255, 255, 255));
        lblPvp.setText("PVP");
        getContentPane().add(lblPvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, -1, -1));

        lblTitleScreen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitleScreen.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleScreen.setText("Galactic Wanderers");
        getContentPane().add(lblTitleScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Back");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/GWTitleScreen.gif"))); // NOI18N
        lblBackground.setAlignmentY(0.0F);
        lblBackground.setMaximumSize(new java.awt.Dimension(1280, 768));
        lblBackground.setMinimumSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPPvpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPPvpMouseClicked
        PickGamemode.this.dispose();
        new PVPCharacterPicking().setVisible(true);
    }//GEN-LAST:event_JPPvpMouseClicked

    private void JPStoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPStoryMouseClicked
        PickGamemode.this.dispose();
        new SMCharacterPicking().setVisible(true);
    }//GEN-LAST:event_JPStoryMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseExited

    private void JPPvpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPPvpMouseEntered
        lblPvp.setForeground(Color.YELLOW);
    }//GEN-LAST:event_JPPvpMouseEntered

    private void JPPvpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPPvpMouseExited
        lblPvp.setForeground(Color.WHITE);
    }//GEN-LAST:event_JPPvpMouseExited

    private void JPStoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPStoryMouseEntered
        lblStorymode.setForeground(Color.YELLOW);
    }//GEN-LAST:event_JPStoryMouseEntered

    private void JPStoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPStoryMouseExited
        lblStorymode.setForeground(Color.WHITE);
    }//GEN-LAST:event_JPStoryMouseExited
    public void background(){
            String filepath="src/Sounds/background2.wav";

            try{
                File musicpath=new File(filepath);
                AudioInputStream audioInput= AudioSystem.getAudioInputStream(musicpath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            }catch(Exception ex){

     }
                            
     }
    public void pnlVisible(){

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickGamemode().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPPvp;
    private javax.swing.JPanel JPStory;
    private javax.swing.JLabel PVPbg;
    private javax.swing.JLabel SMbg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblPvp;
    private javax.swing.JLabel lblStorymode;
    private javax.swing.JLabel lblTitleScreen;
    // End of variables declaration//GEN-END:variables
}
