/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game.ui;

import game.gameLogic.pvp;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import game.characters.Character;

/**
 *
 * @author Wein
 */
public class PickBackground extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Character objChar1 = new Character();
    Character objChar2 = new Character();
    int background=1;
    public PickBackground(){
        initComponents();
    }
    
    public PickBackground(int character1, int character2) {
        initComponents();
        
        objChar1.setChoice(character1);
        objChar2.setChoice(character2);
  
        try{
            File fontStyle = new File("src/fonts/8-bit-hud.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle);
            
            Font titleFont = font.deriveFont(30f);
            lblChoosebg.setFont(titleFont);

            Font nameFont = font.deriveFont(24f);
            btnStart.setFont(nameFont);
            btnBack.setFont(nameFont);
            btnLeft.setFont(nameFont);
            btnRight.setFont(nameFont);
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    } 

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        lblChoosebg = new javax.swing.JLabel();
        btnLeft = new javax.swing.JLabel();
        btnRight = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pickbg = new javax.swing.JLabel();
        PBbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        lblChoosebg.setForeground(new java.awt.Color(255, 255, 255));
        lblChoosebg.setText("Choose Background");
        getContentPane().add(lblChoosebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        btnLeft.setForeground(new java.awt.Color(255, 255, 255));
        btnLeft.setText("<");
        btnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLeftMouseExited(evt);
            }
        });
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        btnRight.setForeground(new java.awt.Color(255, 255, 255));
        btnRight.setText(">");
        btnRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRightMouseExited(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, -1, -1));

        pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickBrettbg.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pickbg, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pickbg, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 640, 360));

        PBbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/charSelectbg.gif"))); // NOI18N
        getContentPane().add(PBbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
        new pvp(objChar1.getChoice(),objChar2.getChoice(), background).setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new PVPCharacterPicking().setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftMouseClicked
        // TODO add your handling code here:    
        if (background == 1)
        {
            background = 4;
        }
        else
        {
            background--;
        }
        switch (background)
        {
            case 1: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickBrettbg.gif")));
                break;
            case 2: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickGabebg.gif")));
                break;
            case 3: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickMiganbg.gif")));
                break;
            case 4: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickSirKhaibg.gif")));
                break;
        }
        
    }//GEN-LAST:event_btnLeftMouseClicked

    private void btnLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftMouseEntered
        // TODO add your handling code here:
        btnLeft.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btnLeftMouseEntered

    private void btnLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftMouseExited
        // TODO add your handling code here:
        btnLeft.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLeftMouseExited

    private void btnRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightMouseClicked
        if (background == 4)
        {
            background = 1;
        }
        else
        {
            background++;
        }
        
        switch (background)
        {
            case 1: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickBrettbg.gif")));
                break;
            case 2: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickGabebg.gif")));
                break;
            case 3: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickMiganbg.gif")));
                break;
            case 4: pickbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/pickSirKhaibg.gif")));
                break;
        }
    }//GEN-LAST:event_btnRightMouseClicked

    private void btnRightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightMouseEntered
        btnRight.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btnRightMouseEntered

    private void btnRightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightMouseExited
        btnRight.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRightMouseExited

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        btnStart.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        btnStart.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnStartMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickBackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickBackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickBackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickBackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickBackground().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PBbg;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnLeft;
    private javax.swing.JLabel btnRight;
    private javax.swing.JLabel btnStart;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChoosebg;
    private javax.swing.JLabel pickbg;
    // End of variables declaration//GEN-END:variables
}
